#!/bin/sh

passwordSegment=""
password=""
passwordLength=0

function randomWord () {
	wordCount=$(wc -l /usr/share/dict/words | awk '{print $1}' ) 
	randomLine=$(jot -r 1 0 $wordCount)     
	passwordSegment=$(awk -v rndmLn=$randomLine 'NR==rndmLn' /usr/share/dict/words)
}

# pass minimum password length & minimum # of words to function
# generatePassword 14 3 for example
function generatePassword () {

	i=0
	echo "passwordLength=$passwordLength"
	while [[ "$passwordLength" -le "$1" ||  "$i" -lt "$2" ]]; do
		randomWord
		if [ $passwordLength -gt 0 ]; then
			password="$password-$passwordSegment"
		else 
			password="$passwordSegment"
		fi
		passwordLength=$( echo -n "$password" | wc -c )
		((i++))

	done
	# generate random number between 1 and 99
	randomNumber=$(jot -r 1 0 99 )
	password="$password$randomNumber"
}

generatePassword $1 $2
echo "$password"

exit 0;
